// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WebSigurnost.Models;

namespace WebSigurnost.Migrations
{
    [DbContext(typeof(KomentarContext))]
    [Migration("20210104082323_Prva")]
    partial class Prva
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebSigurnost.Models.Komentar", b =>
                {
                    b.Property<int>("KomentarId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("KomentarId");

                    b.ToTable("Komentar");
                });
#pragma warning restore 612, 618
        }
    }
}
